name: "linux"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-test-ubuntu:
    name: Build and Test (Ubuntu)
    runs-on: ubuntu-latest
    env:
      BAZEL: bazelisk-linux-amd64
    steps:
    - uses: actions/checkout@v2

    - name: Mount bazel cache
      uses: actions/cache@v2
      with:
        # See https://docs.bazel.build/versions/master/output_directories.html
        path: "~/.cache/bazel"
        key: ${{ runner.os }}-build

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/latest/download/$BAZEL"
        chmod +x $BAZEL

    - name: Build
      run: ./$BAZEL build -c opt //...

    - name: Test
      run: ./$BAZEL test -c opt //... --test_output=errors
