name: "windows"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-test-windows:
    name: Build and Test (Windows)
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Mount bazel cache
      uses: actions/cache@v2
      with:
        # See https://docs.bazel.build/versions/master/output_directories.html
        path: ${{ github.workspace }}/.cache/bazel
        key: ${{ runner.os }}-bazel-${{ hashFiles('WORKSPACE.bazel') }}
        restore-keys: ${{ runner.os }}-bazel

    - name: Install bazelisk
      run: |
        powershell Invoke-WebRequest https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-windows-amd64.exe -OutFile bazel.exe

    - name: Build
      run: ./bazel.exe build -c opt //...

    - name: Test
      run: ./bazel.exe test -c opt //...
